import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

// Import services and models to handle authentication and user data
import 'services/auth_service.dart';
import 'models/user_model.dart';

// Import the Wrapper which handles the initial routing logic
import 'screens/wrapper.dart';

// Import Firebase configuration generated by the FlutterFire CLI
import 'firebase_options.dart';

void main() async {
  // Ensure that the Flutter binding is initialized before calling native code (like Firebase)
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the options for the current platform (Android/iOS/Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Run the root widget of the application
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // StreamProvider listens to the authentication stream from AuthService.
    // It provides the current 'UserModel' (or null if logged out) to the entire widget tree.
    // This allows any widget in the app to access the current user's login state.
    return StreamProvider<UserModel?>.value(
      value: AuthService().user, // The stream being listened to
      initialData: null,         // Initial value before the stream emits data
      child: MaterialApp(
        debugShowCheckedModeBanner: false, // Hides the "Debug" banner in the top right
        title: 'Suggestify',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        // The Wrapper widget checks the provider's user data and decides
        // whether to show the Login Screen or the Home Screen.
        home: const Wrapper(),
      ),
    );
  }
}